apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-svc
spec:
  selector:
    app: apache
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30087
